config/routes.rb
Rails.application.routes.draw do

    root "pages#home"
    get 'pages/home', to: 'pages#home'
    
    resources :recipes
    
    get '/signup', to: 'chefs#new'
    
    resources :chefs, except: [:new]
    
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    
    resources :ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 5}
    belongs_to :chef
    validates :chef_id, presence: true
    default_scope -> {order(updated_at: :desc)}
    has_many :recipe_ingredients
    has_many :ingredient, through: :recipe_ingredients
    has_many :comments, dependent: :destroy         #nếu recipe destroy thì comments cũng destroy theo
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
    before_action :set_recipe, only: [:show, :update, :edit, :destroy]
    before_action :require_user, except: [:show, :index]
    before_action :require_same_user, only: [:edit, :update, :destroy]
    

    def index
        @recipes = Recipe.paginate(page: params[:page], per_page: 5)
    end
    
    def show
    end
    
    def new
        @recipe = Recipe.new
    end
    
    def create
        @recipe = Recipe.new(recipe_params)
        @recipe.chef = current_chef
        if @recipe.save
            flash[:success] = "Recipe create successfully"
            redirect_to recipe_path(@recipe)
        else    
            render 'new'
        end
    end
    
    def edit
    end
    
    def update
        
        if @recipe.update(recipe_params)
            flash[:success] = "Recipe was updated successfully"
            redirect_to recipe_path(@recipe) 
        else
            render 'edit'
        end
    end
    
    def destroy
        Recipe.find(params[:id]).destroy
        flash[:danger] = "Recipe was delete successfully"
        redirect_to recipes_path
    end
    
    private
        def recipe_params
           params.require(:recipe).permit(:name,:description, ingredient_ids: []) 
        end
        def set_recipe
           @recipe = Recipe.find(params[:id])
        end
        def require_same_user
            if current_chef != @recipe.chef and !current_chef.admin?
                flash[:danger] = "You can only edit or delete your own recipe"
                redirect_to recipes_path
            end
        end
end

app/views/recipes/_form.html.erb
<%= render 'share/errors', obj: @recipe %>

<div class="row">
    <div class="col-md-12">
        <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="col-md-2 control-label">
                    <%= f.label :name %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-2 control-label">
                    <%= f.label :description %>
                </div>
                <div class="col-md-8 ">
                    <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter step to create recipe"%>
                </div>
            </div>
            <div class="form-group">
                <div class="row">
                    <div class="col-md-offset-2 col-md-8">
                        <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |cb| %>
                            <% cb.label(class: "checkbox-inline input-checkbox") {cb.check_box(class: "checkbox checkbox1") + cb.text} %>
                        <% end %>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 col-md-offset-2">
                    <%= f.submit class: "btn btn-primary btn-lg btn-xlarge"%>
                </div>
            </div>
        <%end%>
        <div class="col-md-4 col-md-offset-4 colormatch">
            [<%= link_to "Cancel request and return to recipes listing", to: recipes_path %>]
        </div>
    </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
<div class="row">
    <div class="col-md-2 col-md-offset-1">
        <section class="chef_info center">
            <%= gravatar_for(recipe.chef, size: 120) %>
        </section>
    </div>
    <div class="col-md-8 well ">
        <h3><%= link_to recipe.name, recipe_path(recipe) %></h4>
        <p><%= truncate(recipe.description,length: 150) %></p>
        <% if recipe.ingredient.any? %>
            <p>Ingredients: <%=  render recipe.ingredient %> </p>
        <% end %>
        <p>
            <span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by <%= recipe.chef.chefname %> | Updated <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
            <span class = "pull-right"><small>by <%= recipe.chef.chefname.capitalize %></small></span>
        </p>
        <p>
            
        </p>
        <p class = "nut-trang-chu">
            <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?)%>
                <%= link_to "Edit this recipe", edit_recipe_path(recipe), class: "btn btn-xs btn-warning" %>
                <%= link_to "Delete this recipe", recipe_path(recipe), method: :delete, data: {confirm: "Are you sure you want to delete this recipe?"},
                                                           class: "btn btn-xs btn-danger" %>
            <% end %>
        </p>
    </div>
</div>
<% end %>

app/views/recipes/edit.html.erb
<%= render 'share/page_title', title: "edit an existing recipe" %>
<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'share/page_title', title: 'listing all Recipes' %>
<div align="center">
    <%= will_paginate %>
</div>
<%= render 'recipe', obj: @recipes %>
<div align="center">
    <%= will_paginate %> 
</div>

app/views/recipes/new.html.erb
<%= render 'share/page_title', title: "create new recipe" %>
<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'share/page_title', title: @recipe.name %>
<div class="well col-md-8 col-md-offset-2 ">
    <h4 class="center description"><strong>Step: </strong></h4>
    <hr/>
    <%= simple_format(@recipe.description) %>
    <hr>
    <div class="pull-right">
        <p class="center">
            <em>Created by:</em>
        </p>
        <p class="center">
            <%=link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %>
        </p>
        <p class="center">
            <small><%= @recipe.chef.chefname.capitalize %></small>
        </p>  
        <p>
        <small><%= @recipe.chef.chefname %></small>
        <div class="pull-right">Created <%= time_ago_in_words(@recipe.created_at)%> ago</div>
        </p>
    </div>
    <div class="recipe-edit">
        <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
            <%= link_to "Edit this recipe", edit_recipe_path, class: "btn btn-xs btn-warning" %>
            <%= link_to "Delete this recipe", recipe_path, method: :delete, data: {confirm: "Are you sure you want to delete this recipe?"},
                                                           class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-primary" %>                                              
    </div>
</div>