config/routes.rb
Rails.application.routes.draw do

    root "pages#home"
    get 'pages/home', to: 'pages#home'
    
    resources :recipes
    
    get '/signup', to: 'chefs#new'
    
    resources :chefs, except: [:new]
    
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
    
    resources :ingredients
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
    validates :name, presence: true, length: {minimum: 3, maximum: 30}
    validates_uniqueness_of :name
    has_many :recipe_ingredients
    has_many :recipe, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
    before_action :set_ingredient, only: [:show, :edit, :update, :destroy]
    before_action :require_admin, except: [:index, :show]

    def index
        @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
    end
    
    def show
        @ingredient_recipes = @ingredient.recipe.paginate(page: params[:page], per_page: 5)
    end
    
    def create
        @ingredient = Ingredient.new(ingredient_params)
        if @ingredient.save
            flash[:success] = "Create ingredient successfully"   
            redirect_to ingredient_path(@ingredient)
        else 
            render 'new'
        end
    end
    
    def update
        if @ingredient.update(ingredient_params)
            flash[:success] = "Update ingredient successfully"
            redirect_to @ingredient
        else
            render 'edit'
        end
    end
    
    def new
        @ingredient = Ingredient.new
    end
    
    def edit
    
    end
    
    def destroy
        Ingredient.find(params[:id]).destroy
        flash[:danger] = "Ingredient was delete successfully"
        redirect_to ingredients_path
    end
    
    private 
        def set_ingredient
           @ingredient = Ingredient.find(params[:id]) 
        end
        
        def ingredient_params
           params.require(:ingredient).permit(:name)
        end
        def require_admin
            if !logged_in? && (logged_in? and !current_chef.admin?)
                flash[:danger] = "Only admin users can action"
                redirect_to ingredient_path
            end
        end
end

app/views/ingredients/_form.html.erb
<%= render 'share/errors', obj: @ingredient %>

<div class="row">
    <div class="col-md-12">
        <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
            <div class="form-group">
                <div class="col-md-2 control-label">
                    <%= f.label :name %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-10 col-md-offset-2">
                    <%= f.submit(@ingredient.new_record? ? "Add ingredient" : "Update ingredient", class: "btn btn-primary btn-lg btn-xlarge")%>
                </div>
            </div>
        <%end%>
        <div class="col-md-4 col-md-offset-4 colormatch">
            [<%= link_to "Cancel request and return to recipes listing", to: recipes_path %>]
        </div>
    </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class = "badge" ><%= link_to ingredient.name, ingredient_path(ingredient) %>&nbsp; </span>

app/views/ingredients/edit.html.erb
<%=render 'share/page_title', title: "edit ingredient" %>

<%= render 'form' %>

app/views/ingredients/index.html.erb
<%=render 'share/page_title', title: "Listing all Ingredients"%>

<div align= "center">
    <%= will_paginate %>
    <% @ingredients.each do |ing| %>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4">
                    <li class= "chef-title"> <%=link_to ing.name.capitalize, ingredient_path(ing) %></li>
                    <li><small><%= pluralize(ing.recipe.count, "recipe") if ing.recipe %></small></li>
                    <% if logged_in? && current_chef.admin? %>
                        <li><%= link_to "Update ingredient", edit_ingredient_path(ing)%> || <%= link_to "Delete ingredient", ingredient_path(ing), method: :delete, data: {confirm: "Are you want to delete the chef and all associate recipe"} %></li>
                    <% end %>
                </div>
            </div>
        </ul>
    <%end%>
    <%= will_paginate %>
</div>

app/views/ingredients/new.html.erb
<%= render 'share/page_title', title: "create new recipe" %>
<%= render 'form' %>

app/views/ingredients/show.html.erb
<%= render 'share/page_title', title: "#{@ingredient.name}" %>

<% if @ingredient.recipe.count != 0 %>
    <h4 align = "center">Recipe's containing <%= @ingredient.name%></h4>
    <div class="center">
        <%= will_paginate @ingredient_recipes%>
    </div>
    <%= render 'recipes/recipe', obj: @ingredient_recipes %>
    <div class="center">
        <%= will_paginate @ingredient_recipes%>
    </div>
<% else %>
    <h4 class="center">Not ingredient yet!</h4>
<%end%>